/*
 * Timer1.c
 *
 *  Created on: Oct 15, 2021
 *      Author: Mahmoud
 */
#include "Timer1.h"
void Timer1_init(){
#if TIMER1_MODE == TIMER1_NORMAL
	CLR_BIT(TCCR1A, WGM10);
	CLR_BIT(TCCR1A, WGM11);
	CLR_BIT(TCCR1A, WGM12);
#elif TIMER1_MODE == TIMER1_PWM_PHASE_CORRECT_8
	SET_BIT(TCCR1A, WGM10);
	CLR_BIT(TCCR1A, WGM11);
	CLR_BIT(TCCR1A, WGM12);
#elif TIMER1_MODE == TIMER1_PWM_PHASE_CORRECT_9
	CLR_BIT(TCCR1A, WGM10);
	SET_BIT(TCCR1A, WGM11);
	CLR_BIT(TCCR1A, WGM12);
#elif TIMER1_MODE == TIMER1_PWM_PHASE_CORRECT_10
	SET_BIT(TCCR1A, WGM10);
	SET_BIT(TCCR1A, WGM11);
	CLR_BIT(TCCR1A, WGM12);
#elif TIMER1_MODE == TIMER1_CTC
	CLR_BIT(TCCR1A, WGM10);
	CLR_BIT(TCCR1A, WGM11);
	SET_BIT(TCCR1A, WGM12);
#elif TIMER1_MODE == TIMER1_PWM_FAST_8
	SET_BIT(TCCR1A, WGM10);
	CLR_BIT(TCCR1A, WGM11);
	SET_BIT(TCCR1A, WGM12);
#elif TIMER1_MODE == TIMER1_PWM_FAST_9
	CLR_BIT(TCCR1A, WGM10);
	SET_BIT(TCCR1A, WGM11);
	SET_BIT(TCCR1A, WGM12);
#elif TIMER1_MODE == TIMER1_PWM_FAST_10
	SET_BIT(TCCR1A, WGM10);
	SET_BIT(TCCR1A, WGM11);
	SET_BIT(TCCR1A, WGM12);
#endif

#if TIMER1_COMPARE_OUTPUT == COM_OUT_DIS
	CLR_BIT(TCCR1A, COM1A0);
	CLR_BIT(TCCR1A, COM1A1);
#elif TIMER1_COMPARE_OUTPUT == COM_OUT_TOG
	SET_BIT(TCCR1A,COM1A0);
	CLR_BIT(TCCR1A,COM1A1);
#elif TIMER1_COMPARE_OUTPUT == COM_OUT_CLR
	CLR_BIT(TCCR1A,COM1A0);
	SET_BIT(TCCR1A,COM1A1);
#elif TIMER1_COMPARE_OUTPUT == COM_OUT_SET
	SET_BIT(TCCR1A,COM1A0);
	SET_BIT(TCCR1A,COM1A1);
#endif

#if TIMO_PRES == TIMO_NO_CLK
	CLR_BIT(TCCR1, CS10);
	CLR_BIT(TCCR1, CS11);
	CLR_BIT(TCCR1, CS12);
#elif TIMO_PRES == TIMO_NO_PRES
	SET_BIT(TCCR1A, 0);
	CLR_BIT(TCCR1A, 1);
	CLR_BIT(TCCR1A, 2);
#elif TIMO_PRES == TIMO_8_PRES
	CLR_BIT(TCCR1, 0);
	SET_BIT(TCCR1, 1);
	CLR_BIT(TCCR1, 2);
#elif TIMO_PRES == TIMO_64_PRES
	SET_BIT(TCCR1, 0);
	SET_BIT(TCCR1, 1);
	CLR_BIT(TCCR1, 2);
#elif TIMO_PRES == TIMO_256_PRES
	CLR_BIT(TCCR1A, 0);
	CLR_BIT(TCCR1A, 1);
	SET_BIT(TCCR1A, 2);
#elif TIMO_PRES == TIMO_1024_PRES
	SET_BIT(TCCR1A, 0);
	CLR_BIT(TCCR1A, 1);
	SET_BIT(TCCR1A, 2);
#endif
}
void Timer_PWM(void){
	TCCR1A |= (1 << COM1B1) | (1 << WGM11) | (1 << WGM10);
	TCCR1B |= (1 << CS10) | (1 << WGM12);
	OCR1A = 800;
	OCR1B = 0;
}
